#!/bin/bash

for run_file in *.run; do # only possible way to pass multiple files
    ./trec_eval -m ndcg_cut.10 -m set_recall -m official  data/qrel/qrels-covid_d5_j0.5-5.txt "$run_file" |  cut -f 3 | xargs -I {} printf "%s," {} | xargs -I {} printf "%s\n" {} >> trec_log.csv &&
    mkdir -p runs/processed &&
    mv "$run_file" runs/processed
done